language: rust
dist: trusty
services: docker
sudo: required
install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain $TRAVIS_RUST_VERSION
  - source ~/.cargo/env
  - cargo install cross
script: cross test --target $TARGET
matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=i686-unknown-linux-gnu
